### ISSUE TITLE
[DOCS] broken links

### ISSUE THREAD

**Issue by VirginieLemaire** [nightsailor/online-school#10]
### Description

Hi,
Links to "code of conduct" and "contributing" are broken in the README file : need to change `main` into `master` 😉 
example : 

- in the README : `https://github.com/nightsailor/online-school/blob/main/CODE_OF_CONDUCT.md `
- in the repo : ` https://github.com/nightsailor/online-school/blob/master/CODE_OF_CONDUCT.md`

I can do it if you want to ;)

**Comment by angellee177** [comment]
hi, i will take this.

**Comment by VirginieLemaire** [comment]
@angellee177 : I was waiting for this issue to be assigned to me, as told in the step 0 of the CONTRIBUTING

**Comment by angellee177** [comment]
I see, then you can just simply close the PR. :) @VirginieLemaire

**Comment by nightsailor** [comment]
@angellee177 You may have a look at the code to select and make any contribution to the app. Thank you!

**Comment by nightsailor** [comment]
@VirginieLemaire Thanks for identifying [broken links](). Are you submitting the PR to Hacktoberfest?

**Comment by VirginieLemaire** [comment]
Yes ;)

**Comment by nightsailor** [comment]
#12 closes #10

**Comment by nightsailor** [comment]
#12 closes #10
