### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by Vedant-Manjrekar** [nightsailor/online-school#17]
### What would you like to share?

Please add the live link to this website on the github repositiory.

**Comment by nightsailor** [comment]
Hey, Thank you for your suggestion. The website is still in initial stage, So there won't be a live link at this point of time. I hope to add a live link when the web app is improved further.

You can follow the following few easy steps to create a production environment by your self :

- Copy server/example.env to server/.env
- Update Mongo DB connection string in server/.env file

- cd client && yarn build
- cd ../server && yarn start
