### ISSUE TITLE
[DOCS] Remove the requirement to init npm/yarn from contribution guidelines

### ISSUE THREAD

**Issue by Labnann** [nightsailor/online-school#20]
### Description

The purpose of npm/yarn init is to create a package.json. We already have package.json in ./client and ./server. Therefore, we do not need to `npm/yarn init` to build the project.

**Comment by nightsailor** [comment]
Hi @Labnann  ,

Good check ⚡
Please make sure to check any other mistakes in CONTRIBUTING.md. Thank You :)
