### ISSUE TITLE
Update Readme:

### ISSUE THREAD

**Issue by durgeshsahu007** [nightsailor/online-school#22]
### What would you like to share?

Add additional feature on readme

**Comment by nightsailor** [comment]
Hi @durgeshsahu007 ,

Thanks for sharing this. Can you do the implementation of the feature you plan to add on README?

**Comment by durgeshsahu007** [comment]
@nightsailor kindly check #25

**Comment by nightsailor** [comment]
Hi @durgeshsahu007 ,

You didn't mention clearly what you want to contribute in the issue. From your PR it looks like you want to add contributors section which links to wrong repository. The contributors section is already added by #24

**Comment by nightsailor** [comment]
You may have a look at the code to select and make any contribution to the app. Thank you!
