### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by tamalCodes** [nightsailor/online-school#8]
Since this is an Opensource repo - i think there should be ISSUE TEMPLATES for better managing of it ! 

### Here's how they looks : 

![image](https://user-images.githubusercontent.com/72851613/186452667-d4dd17f4-da50-4c10-a579-0ad387b10fe8.png)

### Here's how the forms look : 

![image](https://user-images.githubusercontent.com/72851613/186452781-505a474a-60f6-405f-865b-f4b8d4c05d23.png)

**Comment by nightsailor** [comment]
Hey, The template looks good! I'd appreciate if you can add it to the 'online school'.
